version: '2'

services:
  budgeteer:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
      - "5001:5001"
    links:
      - db

  db:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
