version: '2'

services:
  budgeteer:
    build: .
    env_file:
      - .env
    ports:
      - "443:5000"
    links:
      - db
    volumes:
      - ./:/usr/workdir
  db:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
